/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chooseyourownadventureculminatingtask;

import java.util.ArrayList;

/**
 *
 * @author seeng1309
 */
public class finalFloor extends javax.swing.JFrame {
    //my many global variables
    int count = 0;
    int wait = 0;
    String answers = "";
    String allowedAnswer = "1";
    String allowedAnswer2 = "2";
    String allowedAnswer3 = "3";
    String allowedAnswer4 = "4";
    int Death = (int)Math.ceil(Math.random()*2);
    ArrayList <String> items = new ArrayList();
    // these public static strings are very important, they allow my ariables to be passed through screens
    public static String items1;
    public static String items2;
    public finalFloor() {
        /**very important initialize statement, it checks to see what items you have and 
        * then determines what message it prints out 
        **/
        initComponents();
        // checking for a wand
        if (items2.equals("Wand")) {
            itemsTextArea.append("Note - 1\n");
            itemsTextArea.append("Wand - 1");
            mTTa.append("You see the wizard standing by the door out of the\n"
                    + "tower... He notices you and laughs an evil laugh\n"
                    + "I'll never let you escape my tower! He says wickedly\n"
                    + "But before he can say anything else, you simply zap \n"
                    + "him with you wand and walk out of the tower. \n"
                    + "You have excasped the wizard tower!");
            initializeButton.setEnabled(true);
            answerButton.setEnabled(false);            
        }
        // checking for jonesy mc bonesy
        else if(items2.equals("Jonesy")){
            itemsTextArea.append("Note - 1\n");
            itemsTextArea.append("Jonesy - 1");
            mTTa.append("You see the wizard standing by the door out of the\n"
                    + "tower... He notices you and laughs an evil laugh\n"
                    + "I'll never let you escape my tower! He says wickedly\n"
                    + "However, Jonesy the skeleton launches himself at the\n"
                    + "wizard, shoving him and the wizard through the window\n"
                    + "behind him, as he looks back as he falls, Jonesy says \n"
                    + "\n 'I'll never forget you... friend'"); // I LOVE JONESY MCBONESY SO SO SO SO SO SO SO MUCHHHHHH
            mTTa.append("You have escaped the tower!");
            initializeButton.setEnabled(true);
            answerButton.setEnabled(false);
        }
        // this checks for no items
        else if (items2.equals("a")) {
             mTTa.append("You see the wizard standing by the door out of the\n"
                    + "tower... He notices you and laughs an evil laugh\n");
            mTTa.append("So... You have no wand... and you have no Skeleton\n"
                  + "if you want to survive answer me this one question... is\n"
                  + "Seth a cool guy?\n\n"
                  + "1. Duh\n"
                  + "2. no lol");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTextArea = new javax.swing.JTextArea();
        initializeButton = new javax.swing.JButton();
        lootLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mTTa = new javax.swing.JTextArea();
        answerButton = new javax.swing.JButton();
        inputAnswer = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemsTextArea.setEditable(false);
        itemsTextArea.setColumns(20);
        itemsTextArea.setRows(5);
        jScrollPane2.setViewportView(itemsTextArea);

        initializeButton.setText("Initialize");
        initializeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initializeButtonActionPerformed(evt);
            }
        });

        lootLabel.setText("Gold: 100");

        mTTa.setEditable(false);
        mTTa.setColumns(20);
        mTTa.setFont(new java.awt.Font("Manga Temple", 0, 10)); // NOI18N
        mTTa.setRows(5);
        jScrollPane1.setViewportView(mTTa);

        answerButton.setText("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        inputAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAnswerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lootLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(answerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(initializeButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerButton)
                            .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lootLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initializeButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * if you finish the game and want to play again / return to the start use this button
 * @param evt 
 */
    private void initializeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initializeButtonActionPerformed
        this.setVisible(false);
        new chooseYourOwnAdventureCulminatingTaskFrame().setVisible(true);
    }//GEN-LAST:event_initializeButtonActionPerformed
/**
 * my answer button, which can determine if you win the game and also takes your answer from the text  box
 * @param evt 
 */
    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // checking what you typed
        answers = inputAnswer.getText();
        //the if statement that checks if your answer is allowed
        if (answers.equals(allowedAnswer)) {
            mTTa.setText("Yeah you're right, I am pretty cool\n"
                    + "You win!");
            initializeButton.setEnabled(true);
            answerButton.setEnabled(false);
        }
        else if (answers.equals(allowedAnswer2)) {
            mTTa.setText("Go away I'm great\n"
                    + "You lose");
            initializeButton.setEnabled(true);
            answerButton.setEnabled(false);
        }
    }//GEN-LAST:event_answerButtonActionPerformed

    private void inputAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAnswerKeyTyped

    }//GEN-LAST:event_inputAnswerKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //MY PASS CODE FOR VARIABLES, IMPORTANT
       items1 = args[0];
       items2 = args[1];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalFloor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JButton initializeButton;
    private javax.swing.JTextField inputAnswer;
    private javax.swing.JTextArea itemsTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lootLabel;
    private javax.swing.JTextArea mTTa;
    // End of variables declaration//GEN-END:variables
}
