/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chooseyourownadventureculminatingtask;

import java.util.ArrayList;

/**
 *
 * @author seeng1309
 */
public class floor2 extends javax.swing.JFrame {
    //MANY MORE GLOBAL VARIABLES
    String answers = "";
    String allowedAnswer = "1";
    String allowedAnswer2 = "2";
    String allowedAnswer3 = "3";
    String allowedAnswer4 = "4";
    int Death = (int)Math.ceil(Math.random()*3);
    ArrayList <String> items = new ArrayList();
    public static String items1;
    public static String items2;
    /**
     * Creates new form floor2
     */
    public floor2() {
        //initializing and checking
        initComponents();
        initializeButton.setEnabled(false);
        nextFloorButton.setEnabled(false); 
        // checking for a note, sets your items in the text area for items
        if (items1.equals("Note")) { 
          itemsTextArea.append(items1 + "- 1\n");
          itemsTextArea.append(items2 + "- 1");
          }
          else if (items1.equals("a")) {
              itemsTextArea.setText("");
          }
        //if you have a bone, you get jonesy mcbonesy!
        if (items2.equals("Bone")) {
        mTTa.setText(""); 
        mTTa.append("You enter the second floor... All around you are just\n"
                  + "piles and piles of bones! The bone you picked up from\n"
                  + "the first floor seems to be vibrating in your pocket!\n"
                  + "It flies out of your pocket and attatches to a nearby\n"
                  + "skeleton! THe skeleton springs to life, and\n"
                  + "introduces himself as 'Jonesy McBonesy' Jonsey will \n"
                  + "continue with you on your adventure\n\n"
                  + "You now have two options...\n"
                  + "1. Walk down to the next floor\n"
                  + "2. Climb out the window, and climb down to the next\n"
                  + "floor");
        itemsTextArea.setText("");
        itemsTextArea.append("Note - 1\n");
        itemsTextArea.append("Jonesy - 1");
        items.add("Note");
        items.add("Jonesy");
        }
        //if you have the wand nothing happens, boring
        else if (items2.equals("Wand")) {
        mTTa.setText(""); 
        mTTa.append("You enter the second floor... All around you are just\n"
                  + "piles and piles of bones! This room is boring and \nseems "
                  + "to have nothing special within it... \nYou have two options.\n"
                  + "1. Walk down to the next floor\n"
                  + "2. Climb out the window, and climb down to the next\n"
                  + "floor");
        items.add("Note");
        items.add("Wand");
        }
        // the placeholder, also boring
        else if (items1.equals("a")) {
        mTTa.setText(""); 
        mTTa.append("You enter the second floor... All around you are just\n"
                  + "piles and piles of bones! This room is boring and \nseems "
                  + "to have nothing special within it... \nYou have two options.\n"
                  + "1. Walk down to the next floor\n"
                  + "2. Climb out the window, and climb down to the next\n"
                  + "floor");
        }
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextFloorButton = new javax.swing.JButton();
        lootLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mTTa = new javax.swing.JTextArea();
        answerButton = new javax.swing.JButton();
        inputAnswer = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTextArea = new javax.swing.JTextArea();
        initializeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextFloorButton.setText("Next Floor");
        nextFloorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFloorButtonActionPerformed(evt);
            }
        });

        lootLabel.setText("Gold: 100");

        mTTa.setEditable(false);
        mTTa.setColumns(20);
        mTTa.setFont(new java.awt.Font("Manga Temple", 0, 10)); // NOI18N
        mTTa.setRows(5);
        jScrollPane1.setViewportView(mTTa);

        answerButton.setText("Answer");
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        inputAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAnswerKeyTyped(evt);
            }
        });

        itemsTextArea.setEditable(false);
        itemsTextArea.setColumns(20);
        itemsTextArea.setRows(5);
        jScrollPane2.setViewportView(itemsTextArea);

        initializeButton.setText("Initialize");
        initializeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initializeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lootLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(20, 43, Short.MAX_VALUE)
                        .addComponent(nextFloorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(initializeButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(answerButton)
                            .addComponent(inputAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lootLabel)
                            .addComponent(nextFloorButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initializeButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * This is an extremely important part of my code, it determines what item variables to pass onto the next fame, which also determines how your adventure plays out! I explained the foreign
 * code within the statement, but basically is takes a variable from a array, and turns it into a string, it then opens the next frame (which has code within its run component that opens two voided spots) and declares those two spots as variables, which also has a statement that allows this in the initcomponents section.
 * @param evt 
 */
    private void nextFloorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFloorButtonActionPerformed
        if (items.isEmpty()) {
             String info[]=new String[2];  //creates an array to store variable values. You can increase the size when needed
             info[0]="a"; //put jTextField1's value in the array.
             info[1]="a";
             finalFloor.main(info); // call floor1. Here we create an object of a floor1. We are passing info as arguments to main function.
             this.setVisible(false);
          }
        else if (items.get(1).equals("Wand")) {
             String info[]=new String[2];  //creates an array to store variable values. You can increase the size when needed
             info[0]=items.get(0); //put jTextField1's value in the array.
             info[1]=items.get(1);
             finalFloor.main(info); // call floor1. Here we create an object of a floor1. We are passing info as arguments to main function.
             this.setVisible(false);
         }
         else if (items.get(1).equals("Jonesy")) {
             String info[]=new String[2];  //creates an array to store variable values. You can increase the size when needed
             info[0]=items.get(0); //put jTextField1's value in the array.
             info[1]=items.get(1);
             finalFloor.main(info); // call floor1. Here we create an object of a floor1. We are passing info as arguments to main function.
             this.setVisible(false);
         }
    }//GEN-LAST:event_nextFloorButtonActionPerformed
/**
 * my answer button, which pulls answers from the text box and checks answers to what you want to do
 * @param evt 
 */
    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        answers = inputAnswer.getText(); // the upll code to set answers
         // checking for the first answer
        if (answers.equals(allowedAnswer)) {
                mTTa.setText("");
                mTTa.append("Please continue to the next floor");
                nextFloorButton.setEnabled(true);
                answerButton.setEnabled(false);
         }
        //checking for the second answers, also checking for the method of death
         else if (answers.equals(allowedAnswer2)) {
             mTTa.setText("");
           if (itsYaBoyDeath(0) == 0) {
               mTTa.setText("You have died! Please Re-Initialize ");
               answerButton.setEnabled(false);
               initializeButton.setEnabled(true);
               itemsTextArea.setText("");
         }
           else {
               mTTa.setText("You Look out the window, your feet dangling \nprecariously..."
                       + "Please continue to the next floor");
              nextFloorButton.setEnabled(true);
              answerButton.setEnabled(false);
           }
        }
    }//GEN-LAST:event_answerButtonActionPerformed

    private void inputAnswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAnswerKeyTyped

    }//GEN-LAST:event_inputAnswerKeyTyped
/**
 * if you somehow die here, you can return to the main screen
 * @param evt 
 */
    private void initializeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initializeButtonActionPerformed
        this.setVisible(false);
        new chooseYourOwnAdventureCulminatingTaskFrame().setVisible(true);
    }//GEN-LAST:event_initializeButtonActionPerformed
/**
     * My method to determine if you die
     * @param chanceOfDeath
     * @return 
     */
    public int itsYaBoyDeath (int chanceOfDeath) {
        // the declaration of a new random number
        int value = (int)Math.ceil(Math.random()*3);
        //System.out.println(value);
        //the check of the death
        if (value == Death) {
        chanceOfDeath = 0;
      }
        else if(value != Death){
        chanceOfDeath = 1;
    }
        // returning whatever it gives you
        return chanceOfDeath;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                // VERY IMPORTANT, THIS IS VARIABLE PASS CODE WHICH OPEN TWO VOID SPOTS FOR A CARIABLE TO COME THROUGH
       items1 = args[0];
       items2 = args[1];
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new floor2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JButton initializeButton;
    private javax.swing.JTextField inputAnswer;
    private javax.swing.JTextArea itemsTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lootLabel;
    private javax.swing.JTextArea mTTa;
    private javax.swing.JButton nextFloorButton;
    // End of variables declaration//GEN-END:variables
}
